version: "0.1"
syncs:
  - id: adcf2b78-4304-46b8-a8d2-83341b79622a
    connection_id: 31b56f5e-3686-46e8-b460-da38382041d4
    name: ajksldf
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: dataset_with_one_absurdly_big_record
        target_name: dataset_with_one_absurdly_big_record
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: dataset_with_one_absurdly_big_record.val
            target_name: val
          - unique_id: dataset_with_one_absurdly_big_record.id
            target_name: id
