version: "0.1"
syncs:
  - id: aaccc577-aff6-4e45-8ad7-06c55f0dc396
    connection_id: d62031a5-9ce6-4169-9556-be9f136077f9
    name: jkl
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: demo.source.productcategories
        target_name: productcategories
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: demo.source.productcategories.categoryname
            target_name: categoryname
          - unique_id: demo.source.productcategories.productcategorykey
            target_name: productcategorykey
      - unique_id: demo.source.products
        target_name: products
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: demo.source.products.productkey
            target_name: productkey
          - unique_id: demo.source.products.productcolor
            target_name: productcolor
          - unique_id: demo.source.products.productstyle
            target_name: productstyle
          - unique_id: demo.source.products.productsku
            target_name: productsku
          - unique_id: demo.source.products.productsize
            target_name: productsize
          - unique_id: demo.source.products.modelname
            target_name: modelname
          - unique_id: demo.source.products.productsubcategorykey
            target_name: productsubcategorykey
          - unique_id: demo.source.products.productprice
            target_name: productprice
          - unique_id: demo.source.products.productcost
            target_name: productcost
          - unique_id: demo.source.products.productdescription
            target_name: productdescription
          - unique_id: demo.source.products.productname
            target_name: productname
      - unique_id: demo.source.productsubcategories
        target_name: productsubcategories
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: demo.source.productsubcategories.productcategorykey
            target_name: productcategorykey
          - unique_id: demo.source.productsubcategories.productsubcategorykey
            target_name: productsubcategorykey
          - unique_id: demo.source.productsubcategories.subcategoryname
            target_name: subcategoryname
