version: "0.1"
syncs:
  - id: 3d731f30-fcfd-49d6-a90d-fa04f7d5bc7d
    connection_id: 3678fe77-25b9-4524-8b99-506ac424b498
    name: sdaf
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: blns_dataset_uid
        target_name: blns_dataset
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: blns_dataset_uid.blns_col
            target_name: blns_col
