version: "0.1"
syncs:
  - id: eacb6561-05ec-4472-8539-a8e9d6dd03eb
    connection_id: 72aa44fb-8e28-43bd-8b29-07358f2d7ad4
    name: sync
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        compression: zstd
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: dataset_with_same_name_1
        target_name: dataset_with_same_name
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: dataset_with_same_name_1.id
            target_name: id
