version: "0.1"
syncs:
  - id: 2a712093-d89e-476f-ac81-337644ada1f2
    connection_id: 97731e97-fafb-4b25-aecc-007ba3ffba07
    name: sync 2
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: blns_dataset_uid
        target_name: blns_dataset_1
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: blns_dataset_uid.blns_col
            target_name: blns_col
