version: "0.1"
syncs:
  - id: 7236fade-90c9-4e9a-8d98-17f9ab9c6ef5
    connection_id: 394fac71-2bf0-4c2f-bcc1-2d5f0b592221
    name: wayfare
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: blns_dataset_uid
        target_name: blns_dataset
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: blns_dataset_uid.blns_col
            target_name: blns_col
      - unique_id: dataset
        target_name: dataset
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: dataset.uinteger32
            target_name: uinteger_32
          - unique_id: dataset.array_any
            target_name: array_any
          - unique_id: dataset.geography
            target_name: geography
          - unique_id: dataset.map_huge_int_key
            target_name: map_huge_int_key
          - unique_id: dataset.array_string_min_length
            target_name: array_string_min_length
          - unique_id: dataset.array_string_max_and_min_length
            target_name: array_string_max_and_min_length
          - unique_id: dataset.struct_simple
            target_name: struct_simple
          - unique_id: dataset.array_struct_all
            target_name: array_struct_all
          - unique_id: case_data_field_name
            target_name: case_data_field_name
          - unique_id: dataset.array_uinteger128
            target_name: array_uinteger_128
          - unique_id: dataset.array_integer4
            target_name: array_integer_4
          - unique_id: dataset.array_integer128
            target_name: array_integer_128
          - unique_id: dataset.array_bytes
            target_name: array_bytes
          - unique_id: dataset.decimal_precision_scale
            target_name: decimal_precision_scale
          - unique_id: dataset.integer4
            target_name: integer_4
          - unique_id: dataset.uinteger64
            target_name: uinteger_64
          - unique_id: case_full_name
            target_name: case_full_name
          - unique_id: dataset.array_uinteger64
            target_name: array_uinteger_64
          - unique_id: dataset.decimal_scale
            target_name: decimal_scale
          - unique_id: dataset.array_decimal_precision
            target_name: array_decimal_precision
          - unique_id: dataset.array_struct_simple
            target_name: array_struct_simple
          - unique_id: dataset.array_integer32
            target_name: array_integer_32
          - unique_id: dataset.array_uinteger32
            target_name: array_uinteger_32
          - unique_id: dataset.union_nested
            target_name: union_nested
          - unique_id: dataset.uinteger128
            target_name: uinteger_128
          - unique_id: dataset.bytes
            target_name: bytes
          - unique_id: dataset.json_object
            target_name: json_object
          - unique_id: dataset.array_json
            target_name: array_json
          - unique_id: dataset.integer8
            target_name: integer_8
          - unique_id: dataset.array_date
            target_name: array_date
          - unique_id: dataset.union_simple
            target_name: union_simple
          - unique_id: dataset.uinteger8
            target_name: uinteger_8
          - unique_id: dataset.integer16
            target_name: integer_16
          - unique_id: dataset.decimal_precision
            target_name: decimal_precision
          - unique_id: dataset.boolean
            target_name: boolean
          - unique_id: dataset.float
            target_name: float
          - unique_id: dataset.decimal_huge_precision
            target_name: decimal_huge_precision
          - unique_id: dataset.array_uinteger4
            target_name: array_uinteger_4
          - unique_id: dataset.json
            target_name: json
          - unique_id: dataset.array_boolean
            target_name: array_boolean
          - unique_id: dataset.uinteger4
            target_name: uinteger_4
          - unique_id: dataset.array_decimal
            target_name: array_decimal
          - unique_id: dataset.datetime_with_timezone
            target_name: datetime_with_timezone
          - unique_id: dataset.xml
            target_name: xml
          - unique_id: dataset.datetime_without_timezone
            target_name: datetime_without_timezone
          - unique_id: dataset.any
            target_name: any
          - unique_id: dataset.string
            target_name: string
          - unique_id: dataset.map_any
            target_name: map_any
          - unique_id: dataset.struct_nested
            target_name: struct_nested
          - unique_id: dataset.array_integer8
            target_name: array_integer_8
          - unique_id: dataset.array_datetime_without_timezone
            target_name: array_datetime_without_timezone
          - unique_id: dataset.array_decimal_precision_scale
            target_name: array_decimal_precision_scale
          - unique_id: dataset.uinteger16
            target_name: uinteger_16
          - unique_id: dataset.geometry
            target_name: geometry
          - unique_id: dataset.integer32
            target_name: integer_32
          - unique_id: case_variant_name
            target_name: case_variant_name
          - unique_id: dataset.integer64
            target_name: integer_64
          - unique_id: dataset.array_uinteger16
            target_name: array_uinteger_16
          - unique_id: dataset.string_allowed_values
            target_name: string_allowed_values
          - unique_id: dataset.date
            target_name: date
          - unique_id: dataset.array_decimal_scale
            target_name: array_decimal_scale
          - unique_id: dataset.array_xml
            target_name: array_xml
          - unique_id: dataset.struct_all
            target_name: struct_all
          - unique_id: dataset.array_map
            target_name: array_map
          - unique_id: dataset.string_max_and_min_length
            target_name: string_max_and_min_length
          - unique_id: dataset.array_datetime_with_timezone
            target_name: array_datetime_with_timezone
          - unique_id: dataset.array_integer64
            target_name: array_integer_64
          - unique_id: dataset.array_integer16
            target_name: array_integer_16
          - unique_id: dataset.map
            target_name: map
          - unique_id: dataset.array_uinteger8
            target_name: array_uinteger_8
          - unique_id: dataset.string_max_length
            target_name: string_max_length
          - unique_id: dataset.string_min_length
            target_name: string_min_length
          - unique_id: dataset.map_int_key
            target_name: map_int_key
          - unique_id: dataset.array_float
            target_name: array_float
          - unique_id: dataset.decimal
            target_name: decimal
          - unique_id: dataset.array_string_allowed_values
            target_name: array_string_allowed_values
          - unique_id: dataset.array_geometry
            target_name: array_geometry
          - unique_id: dataset.time
            target_name: time
          - unique_id: dataset.integer128
            target_name: integer_128
          - unique_id: dataset.array_string_max_length
            target_name: array_string_max_length
          - unique_id: dataset.array_string
            target_name: array_string
          - unique_id: dataset.array_geography
            target_name: array_geography
          - unique_id: dataset.array_time
            target_name: array_time
          - unique_id: dataset.array_union
            target_name: array_union
      - unique_id: dummy_source_dataset_uid
        target_name: dummy_source_dataset
        data_extraction_config:
          name: Full Extract
          values: null
        loading_option:
          type: Truncate and insert
        data_fields:
          - unique_id: dummy_source_dataset_uid.dummy_col
            target_name: dummy_col
