version: "0.1"
syncs:
  - id: 4cfe43c4-1aa9-4f4a-9332-e2404897f7e3
    connection_id: bb13cf57-85d9-4c7e-be6a-2aa0a2c4b990
    name: with deletes
    description: ""
    extraction_concurrency:
      num_workers: 1
    file_storage:
      folder_path: ""
      file_details:
        type: PARQUET
      batch_size: 250000
      delete_after_sync: true
    data_sets:
      - unique_id: dataset_with_deletes_uid
        target_name: dataset_with_deletes
        data_extraction_config:
          name: Incremental
          values:
            percent_deletes: "0.1"
            random_deletes: true
        loading_option:
          type: Upsert
          delete_mode: hard
          primary_keys:
            - dataset_with_deletes_uid.id
        data_fields:
          - unique_id: dataset_with_deletes_uid.id
            target_name: id
          - unique_id: dataset_with_deletes_uid.val
            target_name: val
