create or replace view {{ source('wayfare_unmanaged', 'PRODUCTS') }} (
    MODELNAME,
    PRODUCTCOLOR,
    PRODUCTDESCRIPTION,
    PRODUCTKEY,
    PRODUCTNAME,
    PRODUCTPRICE,
    PRODUCTSIZE,
    PRODUCTSKU,
    PRODUCTSTYLE,
    PRODUCTSUBCATEGORYKEY,
    _WAYFARE_CREATED_AT,
    _WAYFARE_UPDATED_AT
) as (
    select
        PRODUCTS.MODELNAME as MODELNAME,
        PRODUCTS.PRODUCTCOLOR as PRODUCTCOLOR,
        PRODUCTS.PRODUCTCOST as PRODUCTCOST,
        PRODUCTS.PRODUCTDESCRIPTION as PRODUCTDESCRIPTION,
        PRODUCTS.PRODUCTKEY as PRODUCTKEY,
        PRODUCTS.PRODUCTNAME as PRODUCTNAME,
        PRODUCTS.PRODUCTPRICE as PRODUCTPRICE,
        PRODUCTS.PRODUCTSIZE as PRODUCTSIZE,
        PRODUCTS.PRODUCTSKU as PRODUCTSKU,
        PRODUCTS.PRODUCTSTYLE as PRODUCTSTYLE,
        PRODUCTS.PRODUCTSUBCATEGORYKEY as PRODUCTSUBCATEGORYKEY,
        PRODUCTS._WAYFARE_CREATED_AT as _WAYFARE_CREATED_AT,
        PRODUCTS._WAYFARE_UPDATED_AT as _WAYFARE_UPDATED_AT
    from {{ source('wayfare_unmanaged', 'PRODUCTS') }} as PRODUCTS
);
