create or replace view DEMO.PUBLIC.STG_PRODUCTS (
    MODELNAME,
    PRODUCTCOLOR,
    PRODUCTDESCRIPTION,
    PRODUCTKEY,
    PRODUCTNAME,
    PRODUCTPRICE,
    PRODUCTSIZE,
    PRODUCTSKU,
    PRODUCTSTYLE,
    PRODUCTSUBCATEGORYKEY,
    _WAYFARE_CREATED_AT,
    _WAYFARE_UPDATED_AT
) as (
    select
        PRODUCTS.MODELNAME as MODELNAME,
        PRODUCTS.PRODUCTCOLOR as PRODUCTCOLOR,
        -- products.productcost as productcost,
        PRODUCTS.PRODUCTDESCRIPTION as PRODUCTDESCRIPTION,
        PRODUCTS.PRODUCTKEY as PRODUCTKEY,
        PRODUCTS.PRODUCTNAME as PRODUCTNAME,
        PRODUCTS.PRODUCTPRICE as PRODUCTPRICE,
        PRODUCTS.PRODUCTSIZE as PRODUCTSIZE,
        PRODUCTS.PRODUCTSKU as PRODUCTSKU,
        PRODUCTS.PRODUCTSTYLE as PRODUCTSTYLE,
        PRODUCTS.PRODUCTSUBCATEGORYKEY as PRODUCTSUBCATEGORYKEY,
        PRODUCTS._WAYFARE_CREATED_AT as _WAYFARE_CREATED_AT,
        PRODUCTS._WAYFARE_UPDATED_AT as _WAYFARE_UPDATED_AT
    from DEMO.PUBLIC.PRODUCTS as PRODUCTS
);
